import { Injectable, ConflictException, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { Campaign, CampaignDocument } from './schemas/campaign.schema';
import { CreateCampaignDto } from './dto/create-campaign.dto';

@Injectable()
export class CampaignsService {
  constructor(
    @InjectModel(Campaign.name)
    private readonly campaignModel: Model<CampaignDocument>,
  ) {}

  async create(dto: CreateCampaignDto): Promise<CampaignDocument> {
    const created = new this.campaignModel({
      ...dto,
      startDate: new Date(dto.startDate),
      endDate: new Date(dto.endDate),
    });
    return created.save();
  }

  async findAll(): Promise<CampaignDocument[]> {
    return this.campaignModel.find().exec();
  }

  async findOne(id: string): Promise<CampaignDocument> {
    const campaign = await this.campaignModel.findById(id).exec();
    if (!campaign) {
      throw new NotFoundException(`Campaign with ID "${id}" not found`);
    }
    return campaign;
  }

  async update(id: string, dto: any): Promise<CampaignDocument> {
    const data = { ...dto };
    if (dto.startDate) data.startDate = new Date(dto.startDate);
    if (dto.endDate) data.endDate = new Date(dto.endDate);

    const updated = await this.campaignModel.findByIdAndUpdate(id, data, { new: true }).exec();
    if (!updated) {
      throw new NotFoundException(`Campaign with ID "${id}" not found`);
    }
    return updated;
  }

  async remove(id: string): Promise<CampaignDocument> {
    const deleted = await this.campaignModel.findByIdAndDelete(id).exec();
    if (!deleted) {
      throw new NotFoundException(`Campaign with ID "${id}" not found`);
    }
    return deleted;
  }

  async getCampaignPerformance(campaignId: string): Promise<any> {
    const campaign = await this.findOne(campaignId);
    
    // Dynamic access to other models to avoid circular imports
    const leadModel = this.campaignModel.db.model('Lead');
    const paymentModel = this.campaignModel.db.model('Payment');

    const cid = new Types.ObjectId(campaignId);

    const totalLeads = await leadModel.countDocuments({ campaign: cid, isDeleted: { $ne: true } }).exec();
    if (totalLeads === 0) {
      return {
        campaign,
        totalLeads: 0,
        contactedLeads: 0,
        contactRate: 0,
        meetingScheduled: 0,
        meetingRate: 0,
        demoLessons: 0,
        demoRate: 0,
        convertedStudents: 0,
        conversionRate: 0,
        revenue: 0,
        roi: 0,
      };
    }

    const contactedLeads = await leadModel.countDocuments({ 
      campaign: cid, 
      status: { $ne: 'NEW_LEAD' }, 
      isDeleted: { $ne: true } 
    }).exec();

    const meetingScheduled = await leadModel.countDocuments({ 
      campaign: cid, 
      status: { $in: ['MEETING_SCHEDULED', 'DEMO_LESSON', 'REGISTERED', 'CONVERTED'] },
      isDeleted: { $ne: true }
    }).exec();

    const demoLessons = await leadModel.countDocuments({ 
      campaign: cid, 
      status: { $in: ['DEMO_LESSON', 'REGISTERED', 'CONVERTED'] },
      isDeleted: { $ne: true }
    }).exec();

    const convertedStudents = await leadModel.countDocuments({ 
      campaign: cid, 
      status: 'CONVERTED',
      isDeleted: { $ne: true }
    }).exec();

    // Sum revenue from payments generated by students converted from this campaign
    const convertedLeadsList = await leadModel.find({ campaign: cid, status: 'CONVERTED' }, { phone: 1 }).exec();
    const phoneList = convertedLeadsList.map(l => l.phone);

    // Find student profiles corresponding to these phone numbers
    const studentProfileModel = this.campaignModel.db.model('StudentProfile');
    const profiles = await studentProfileModel.find({ studentPhone: { $in: phoneList } }).exec();
    const studentUserIds = profiles.map(p => p.userId);

    const payments = await paymentModel.aggregate([
      {
        $match: {
          studentId: { $in: studentUserIds },
          status: 'PAID',
          amount: { $gt: 0 }
        }
      },
      {
        $group: {
          _id: null,
          total: { $sum: '$amount' }
        }
      }
    ]).exec();

    const revenue = payments.length > 0 ? payments[0].total : 0;
    const roi = campaign.budget > 0 ? ((revenue - campaign.budget) / campaign.budget) * 100 : 0;

    return {
      campaign,
      totalLeads,
      contactedLeads,
      contactRate: Math.round((contactedLeads / totalLeads) * 100),
      meetingScheduled,
      meetingRate: Math.round((meetingScheduled / totalLeads) * 100),
      demoLessons,
      demoRate: Math.round((demoLessons / totalLeads) * 100),
      convertedStudents,
      conversionRate: Math.round((convertedStudents / totalLeads) * 100),
      revenue,
      roi: Math.round(roi),
    };
  }
}
